# The information we save about the api access to the fediverse (tokens, urls and more)
mastodon:
  base: https://example.com
  client_id: SuperSecretToken
  client_secret: SuperSecretToken
  redirect: https://example.com/redirect
  token: SuperSecretToken

# Your wordnik api key here
wordnik:
  api_token:

# The path to the local dictionary (relative to the execution path, or you can use an absolute path)
local_dictionary: ./assets/dictionary.txt

# The word that will be appended to the adjectives.
appended_word: myWord
